version: "3"

services:
  jupyter:
    image: ogrisel/distributed:latest
    command: start-notebook.sh
    ports:
       - "8888:8888"
    networks:
      - distributed
    links:
        - dscheduler
    container_name: jupyter

  dscheduler:
    image: ogrisel/distributed:latest
    ports:
     - "8786:8786"
     - "9786:9786"
     - "8787:8787"
    command: start-dscheduler.sh
    networks:
      - distributed
    container_name: dscheduler

  dworker:
    image: ogrisel/distributed:latest
    command: start-dworker.sh
    networks:
      - distributed
    links:
        - dscheduler

networks:
  distributed:
    # Enable multi-host communication
    driver: overlay
    # Single host communication
    #driver: bridge
